### ISSUE TITLE
new sources again

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [Fadavvi/Yara-Repo#2]
please be so kind and add:

   https://gist.github.com/pedramamini/c586a151a978f971b70412ca4485c491
   https://github.com/airbnb/binaryalert/tree/master/rules/public
   https://github.com/codewatchorg/Burp-Yara-Rules
   https://github.com/karttoon/binsequencer
   https://github.com/DidierStevens/DidierStevensSuite
   https://github.com/fideliscyber/indicators/tree/master/yararules
   https://github.com/fireeye/red_team_tool_countermeasures
   https://github.com/f0wl/yara_rules
   https://github.com/EmersonElectricCo/fsf/tree/master/fsf-server/yara
   https://github.com/jeFF0Falltrades/YARA-Signatures
   https://koodous.com/rulesets
   https://github.com/Loginsoft-Research
   https://github.com/malice-plugins/yara/tree/master/rules
   https://malpedia.caad.fkie.fraunhofer.de/api/get/yara/auto/zip
   https://github.com/mikesxrs/Open-Source-YARA-rules
   https://github.com/tylabs/quicksand_lite
   https://github.com/rastrea2r/rastrea2r
   https://github.com/securitymagic/yara
   https://github.com/inv-ds-research/yaraml_rules
   https://github.com/SpiderLabs/malware-analysis/tree/master/Yara
   https://github.com/StrangerealIntel/DailyIOC
   https://github.com/t4d/PhishingKit-Yara-Rules
   https://github.com/VectraThreatLab/reyara
   https://github.com/x64dbg/yarasigs
   https://github.com/wrayjustin/yaids
   https://github.com/DiabloHorn/yara4pentesters

**Comment by Fadavvi** [comment]
I'll add new sources next weekend. Thanks for sharing.

**Comment by Fadavvi** [comment]
https://github.com/codewatchorg/Burp-Yara-Rules (out of scope)
https://github.com/karttoon/binsequencer (Rule maker/app)
https://github.com/DidierStevens/DidierStevensSuite (.exe and .py files)
https://github.com/Loginsoft-Research (Not any yara rule found/app)
https://github.com/mikesxrs/Open-Source-YARA-rules (too old)
https://github.com/rastrea2r/rastrea2r (yara rule not found)
https://github.com/inv-ds-research/yaraml_rules (yara rule not found)
https://github.com/VectraThreatLab/reyara (duplicate)
https://github.com/wrayjustin/yaids (app)
https://github.com/DiabloHorn/yara4pentesters (out of scope)

Others added.
